### ISSUE TITLE
Example commands in docs mention `.htaccess`, while implying `.htpasswd`

### ISSUE THREAD

**Issue by MichaelSchneeberger** [pypiserver/pypiserver#103]
When starting the pypi-server I get an error message saying "malformed htpasswd file". I get the error message even if the .htpasswd file does not exist. What is causing the error?

 Here is the entire Traceback:

```console
C:\Data>pypi-server -p 8080 -P packages\.htaccess packages
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pypi-server.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pypiserver\__main__.py", line 293, in main
    app = pypiserver.app(**vars(c))
  File "c:\python27\lib\site-packages\pypiserver\__init__.py", line 124, in app
    config, packages = core.configure(**kwds)
  File "c:\python27\lib\site-packages\pypiserver\core.py", line 47, in configure
    htPsswdFile = HtpasswdFile(c.password_file)
  File "c:\python27\lib\site-packages\passlib\apache.py", line 583, in __init__
    super(HtpasswdFile, self).__init__(path, **kwds)
  File "c:\python27\lib\site-packages\passlib\apache.py", line 166, in __init__
    self.load()
  File "c:\python27\lib\site-packages\passlib\apache.py", line 236, in load
    self._load_lines(fh)
  File "c:\python27\lib\site-packages\passlib\apache.py", line 261, in _load_lines
    key, value = parse(line, idx+1)
  File "c:\python27\lib\site-packages\passlib\apache.py", line 590, in _parse_record
    % lineno)
ValueError: malformed htpasswd file (error reading line 1)
```

see: http://stackoverflow.com/questions/34635226/malformed-htpasswd-file-error-message-when-starting-pypi-server

**Comment by ankostis** [comment]
The *pypiserver* does not support `.htaccess` files; this is an Apache-only feature. it just reuses the  `.htpasswd` file-format from Apache.
Additionally, the `htpasswd` file better not to be located inside the `packages` folder, so it is impossible for *pypiserver* to serve it by mistake, and reveal its contents.  

Please reopen if that was not the case and/or my response is invalid.

**Comment by ankostis** [comment]
@MichaelSchneeberger said at stackoverflow: 
> You said that "the pypiserver does not support .htaccess files;" But why is it written on github.com/pypiserver/pypiserver to start the pypi-server with the .htaccess file: "./pypi-server -p 8080 -P .htaccess ~/packages &"? – MikeSchneeberger

Thank you indeed the docs are wrong here.
