### ISSUE TITLE
Problem uploading packages

### ISSUE THREAD

**Issue by delhora** [pypiserver/pypiserver#120]
Hello!

I've fresh pypiserver installation just for testing proposes:

Start  server: 

`pypi-server -p 8081 -P htpasswd.txt /opt/packages/ &`

Everything seems fine, but when I try to upload a package with:

`python setup.py sdist upload -r local`

I got the following error at server:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 923, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 1845, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/_app.py", line 45, in protector
    if not config.auther(*request.auth):
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/core.py", line 90, in auth_by_htpasswd_file
    htPsswdFile.load_if_changed()
AttributeError: 'HtpasswdFile' object has no attribute 'load_if_changed'
xxx.xxx.xx.xx- - [11/Mar/2016 10:54:30] "POST / HTTP/1.1" 500 1665
```

My pypirc:

```
[distutils]
index-servers =
  pypi
  local

[pypi]
repository=https://pypi.python.org/pypi
username=foo
password=bar

[local]
repository: http://repos.mycompany.com:8081
username: foo
password: bar
```

Thanks in advance!

**Comment by mplanchard** [comment]
Could you give us some information about what type of system you're running? My initial instinct is that your passlib.apache may be significantly out of date. The `load_if_changed` parameter was added in version 1.6, and the old `load` method was removed in version 1.8.

**Comment by delhora** [comment]
Hello!

You are right sir!
```
pip install passlib --upgrade
Collecting passlib
  Downloading passlib-1.6.5-py2.py3-none-any.whl (317kB)
    100% |████████████████████████████████| 327kB 4.1MB/s 
Installing collected packages: passlib
  Found existing installation: passlib 1.5.3
    Uninstalling passlib-1.5.3:
      Successfully uninstalled passlib-1.5.3
Successfully installed passlib-1.6.5
```

and now it's working and can upload packages!

Thank you very much!

**Comment by ankostis** [comment]
Excellent research @mplanchard, we should add these version-limits to `setup.py`.
