### ISSUE TITLE
pypiserver with recent pip suddenly results in credentials prompt

### ISSUE THREAD

**Issue by JonasT** [pypiserver/pypiserver#175]
We have a project which uses an automatically installed pypiserver and pip which we use for many months already. It just serves packages from a folder directly, with no authentication or special setup over plain HTTP to which we connect with pip using `--trusted-host` and `--extra-index` to install the packages on another machine in the local network.

However, with recent pypiserver & pip this now suddenly gives us credentials prompts which leads pip to abort:

```
pip3 --trusted-host 172.17.0.1 install --extra-index http://172.17.0.1:8765/ daphnetf.hermes
Collecting daphnetf.hermes
User for 172.17.0.1:8765: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.4/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.4/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/local/lib/python3.4/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/local/lib/python3.4/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/local/lib/python3.4/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/local/lib/python3.4/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/sessions.py", line 602, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 181, in handle_401
    username = six.moves.input("User for %s: " % parsed.netloc)
EOFError: EOF when reading a line
```

I don't think I changed anything on our side regarding the use of pypiserver and pip (although I might be wrong) so I wonder if this was caused by a recent update of pypiserver or pip? If yes, is there any way we can avoid this?

**Comment by JonasT** [comment]
I just noticed we accidentally used git master because of an incompatibility with pip we had a long while ago. So this is only broken on git master, with the latest regular pypi release there is no such problem!

**Comment by mplanchard** [comment]
Hi @JonasT, sorry for the lack of movement on this. I think myself and ankostis have both been fairly busy with job stuff. Is this still occurring with the current master and current versions of pip?

**Comment by alexntt** [comment]
Hi:

I was testing the `--pre` version which includes the new fallback URL, and I think I'm getting this.

```
# pip freeze
...
pypiserver==1.2.1.dev0
...
# pypi-server -o -p 80 -P /srv/pypi/.htaccess /srv/pypi
```

If I run in other terminal:

```
$ pip install -i http://pypi.example.com --trusted-host pypi.example.com Django
Collecting Django
User for pypi.example.com: ^COperation cancelled by user
```

and on the pypiserver console log:

```
172.17.0.4 - - [14/Nov/2017 08:16:28] "GET /django/ HTTP/1.1" 303 0
172.17.0.4 - - [14/Nov/2017 08:16:28] "GET /simple/django/ HTTP/1.1" 401 725
```

I tried using `-a update`, but it doesn't seem to do anything (which I think is logical- it's the default).

I'm reverting to the non-pre version, but I can do more testing if required.

**Comment by mplanchard** [comment]
This seems like it may be the same bug as #186 and the subject of ongoing conversation in #179

**Comment by mplanchard** [comment]
@alexntt @JonasT if possible, could you verify that the latest pre-release, `1.2.1rc0` has resolved these issues?

**Comment by alexntt** [comment]
I updated to that version and it doesn't seem to be prompting for authentication any more. We will leave it running and report back if there are other issues.

**Comment by mplanchard** [comment]
I'm going to go ahead and close this for now. Feel free to respond and re-open if the issue recurs.
