### ISSUE TITLE
fallback does not work for different package versions ?

### ISSUE THREAD

**Issue by AdamSharon** [pypiserver/pypiserver#177]
Hi,
This seems like a weird behaviour - the fallback does not work if I ask for a package the repo has but in a different version. 
If I want to pip-install the package "paramiko==1.15.2" and my pypiserver repo have paramiko-2.1.2, I would expect that the fallback be triggered and i'll get the package. instead, I get "Could not find a version that satisfies the requirement".
the fallback works fine for new packages. 

Thanks.

**Comment by mplanchard** [comment]
You mean the fallback to PyPI? Or are you saying you would expect it to
install paramiko 2.1.2 from the pypiserver?

**Comment by AdamSharon** [comment]
Yes, the fallback to PyPI. I would expect to get  "paramiko==1.15.2" from PyPI, just like if I try to pip-install "requests", and my pypiserver does not contain any version of requests.

**Comment by mplanchard** [comment]
Could you paste the verbose output of your pip install command here?
They've been making a lot of changes to the API at the PyPA, so it could be
related to that.

**Comment by AdamSharon** [comment]
sure. 

------
C:\venv2\Scripts>pip install paramiko==1.15.2 -i http://localhost:8036/ --verbose --no-cache-dir
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
Collecting paramiko==1.15.2
  1 location(s) to search for versions of paramiko:
  *http://localhost:8036/paramiko/
  Getting page http://localhost:8036/paramiko/
  Starting new HTTP connection (1): localhost
  "GET /paramiko/ HTTP/1.1" 303 0
  Resetting dropped connection: localhost
  "GET /simple/paramiko/ HTTP/1.1" 200 791
  Analyzing links from page http://localhost:8036/simple/paramiko/
    Found link http://localhost:8036/packages/paramiko-2.1.2-py2.py3-none-any.whl#md5=4be9481e959997f7416f35b3f34ae297 (from http://localhost:8036/simple/paramiko/), version: 2.1.2
    Found link http://localhost:8036/packages/paramiko-2.2.1-py2.py3-none-any.whl#md5=7af00410fe367657f6023616e227c05c (from http://localhost:8036/simple/paramiko/), version: 2.2.1
    Found link http://localhost:8036/packages/paramiko-2.3.0-py2.py3-none-any.whl#md5=a6abc2305c388e8b5daf04df11486868 (from http://localhost:8036/simple/paramiko/), version: 2.3.0
    Found link http://localhost:8036/packages/paramiko-2.3.1-py2.py3-none-any.whl#md5=10c2a6c9796515f168a68db63d03fbf7 (from http://localhost:8036/simple/paramiko/), version: 2.3.1
  Could not find a version that satisfies the requirement paramiko==1.15.2 (from versions: 2.1.2, 2.2.1, 2.3.0, 2.3.1)
Cleaning up...
No matching distribution found for paramiko==1.15.2
Exception information:
Traceback (most recent call last):
  File "c:\venv2\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\venv2\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\venv2\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\venv2\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "c:\venv2\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\venv2\lib\site-packages\pip\index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for paramiko==1.15.2

**Comment by mplanchard** [comment]
Looks like pip isn't even trying to search PyPI. Generally it should say
there are two locations to search. Do you have a pip config file in any of
the locations listed here?
https://pip.pypa.io/en/stable/user_guide/#config-file

If so, could you paste the contents of the file, minus any passwords or
other sensitive information?

**Comment by AdamSharon** [comment]
there is no pip config file on my system. 
There is just one location, the localhost (this is the pypiserver). this is my main and only index in the pip command, but this does not matter when there are no versions of a package on the pypiserver. see attached example, there is just 1 location but the links still come from pypi. 
when I pip-install a package (simplejson) my pypiserver does not have -  this is the start, full file attached
[logver.txt](https://github.com/pypiserver/pypiserver/files/1341006/logver.txt)
 

Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Config variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
Collecting simplejson
  1 location(s) to search for versions of simplejson:
  * http://localhost:8036/simplejson/
  Getting page http://localhost:8036/simplejson/
  Starting new HTTP connection (1): localhost
  "GET /simplejson/ HTTP/1.1" 303 0
  Resetting dropped connection: localhost
  "GET /simple/simplejson/ HTTP/1.1" 303 0
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/simplejson/ HTTP/1.1" 200 13378
  Analyzing links from page https://pypi.python.org/simple/simplejson/
    Found link https://pypi.python.org/packages/00/21/2f3234aac78dac7a585cc6c9a1911d4618b20ae7f800b2ae60cb53395555/simplejson-3.0.7.tar.gz#md5=f674e9035aee1064dae90b22aa76ea98 (from https://pypi.python.org/simple/simplejson/), version: 3.0.7
    Found link https://pypi.python.org/packages/00/d2/4cf1c749787c526b4177eec3eed9d39f94f6db0a5f3b3b9e438d9fa22cfe/simplejson-3.4.0.tar.gz#md5=c076e04916679e4b08ec30f23844fbbf (from https://pypi.python.org/simple/simplejson/), version: 3.4.0
    Found link https://pypi.python.org/packages/03/b5/0c05aa0c96191c0a9e802947c07805183a39b7293210a31873cc8a27c081/simplejson-1.9.3.tar.gz#md5=321f7ad3a347e5a11814bcfecf8b9d11 (from https://pypi.python.org/simple/simplejson/), version: 1.9.3

**Comment by mplanchard** [comment]
Okay, I see what you're saying. This is caused by the logic that determines what packages we do or don't have, and when to fall back.

`find_packages` filters packages by their name (not their version):

```python
def find_packages(pkgs, prefix=""):
    prefix = normalize_pkgname(prefix)
    for x in pkgs:
        if prefix and x.pkgname_norm != prefix:
            continue
yield x
```

and the fallback is determined by whether or not `find_packages()` returns anything:

```
@app.route("/simple/:prefix/")
@auth("list")
def simple(prefix=""):
    # PEP 503: require normalized prefix
    normalized = core.normalize_pkgname(prefix)
    if prefix != normalized:
        return redirect('/simple/{0}/'.format(normalized), 301)

    files = sorted(core.find_packages(packages(), prefix=prefix),
                   key=lambda x: (x.parsed_version, x.relfn))
    if not files:
        if config.redirect_to_fallback:
            return redirect("%s/%s/" % (config.fallback_url.rstrip("/"), prefix))
        return HTTPError(404)

    fp = request.fullpath
    links = [(os.path.basename(f.relfn),
              urljoin(fp, "../../packages/%s" % f.fname_and_hash(config.hash_algo)))
             for f in files]
    tmpl = """\
    <html>
        <head>
            <title>Links for {{prefix}}</title>
        </head>
        <body>
            <h1>Links for {{prefix}}</h1>
            % for file, href in links:
                 <a href="{{href}}">{{file}}</a><br>
            % end
        </body>
    </html>
    """
return template(tmpl, prefix=prefix, links=links)
```

I'm not sure that this isn't intentional, because if you're specifying the pypiserver as the only index, and you have placed a package of a given version there, it seems like it would be reasonable to assume that your intention is to only have *that* version available, to prevent clients from downloading, for example, a bad version from PyPI.

I'd like to think about this a bit and look through old issues. I'm open to feedback, but I can definitely see the rationale in *not* falling back in this case. If we decided to keep it the way it is, I do agree that the documentation should be clearer. `disable redirect to real PyPI index for packages not found in the local index` could definitely be explicit in mentioning that the fallback is not triggered when a package (but not its specific version) isn't found in the index.

Thoughts?

As a workaround, you can of course add that version to your index, or specify pypi.python.org as an extra index URL in your pip command.

**Comment by AdamSharon** [comment]
Ok, the documentation will probably be a lot better. 
I see your point about the version problem. you're saying clients would like to pin a specific version using pypiserver. I guess it's dependent on the use case, I think that "fallback" should mean "pypiserver can't get your package, here it is from somewhere else" and if you don't want that just cancel the fallback. 

The workarounds that you suggested are not good for us, we have connectivity issues and permission issues that prevent us from doing it. 

Anyway, if you have some "quick and dirty" solution for this I'll be happy to get it and use it. in a forked repo of course, so this one will stay as intended. 

Thank you very much for the quick answer.

**Comment by mplanchard** [comment]
So you're not able to upload the specific versions that you need, remove the higher versioned package, or adjust the clients to request a version range?

**Comment by doppleware** [comment]
Hi,
To complement what @AdamSharon is saying, we're using pypiserver as a private server with a fallback to global PyPi. We don't have control over what the client (users) requests.
For our use case, not finding a package at all in pypiserver or not finding the package in the requested range both fall under the same category of '**what you asked for isn't there**' and for both options we need pypiserver to fallback to global Pypi. After all, different version of the same package can live side by side just like separate packages so in both cases we're talking about independent entities.
Is there some code change we can make it PyPi server to get that to work ?

Thanks!
Roni

**Comment by mplanchard** [comment]
Thanks for the feedback!

I'm going add a global "fallback in any situation" option, but I am certain we have users relying on the current behavior to, for example, ensure that clients can only receive the desired version of a package. I don't want to break their workflow, so this will wind up being an additional option.

I don't think it'll be too complicated, so hopefully I'll have time this week to get it in.

**Comment by AdamSharon** [comment]
That's awesome, thank you very much. looking forward to the fix.

**Comment by doppleware** [comment]
Wow really great to hear. Thanks!!

**Comment by mplanchard** [comment]
@AdamSharon and @doppleware - I got some time to work on this tonight. It wound up being a bit more complicated than I envisioned, because of the way `pip` works. To make a long story short, pip doesn't give us an opportunity between getting a list of server packages and saying "nope, that version isn't available" to make a fallback request. So, I wound up getting the list of packages directly from the fallback and appending them to regular package list with the proper URLs, which should allow pip to function normally.

I've got it largely working over on my `alternate-fallback` branch ([here](https://github.com/mplanchard/pypiserver/tree/alternate-fallback)) if you'd like to test it out. To enable it, you'll need to specify "--fallback-strategy="version"".

Things that I'm pretty sure are not yet working:
* SSL in Python 3
* Ensuring that we don't bomb on unexpected failures to connect to the fallback

I probably won't have time to work on this again until the weekend, but let me know if you try it and find any bugs.

**Comment by mplanchard** [comment]
@AdamSharon & @doppleware - I believe I was able to get my branch fully functional this afternoon. SSL seems to be working just fine, and I also resolved the issue of potential duplicate versions between the pypiserver index and the fallback URL (by deferring to the local index), as well as preventing the server from bombing on most foreseeable connection errors.

If you're able to validate that this works as you'd expect, I would appreciate it.

**Comment by doppleware** [comment]
@mplanchard  that's really awesome thanks!
Sorry for the slow responses - we're located in Israel and most of us are on vacation due to the Jewish holidays.. :)  We will definitely check this change early next week.

Thanks again!

**Comment by pawamoy** [comment]
IMO pypiserver's fallback mechanism is convenient, but should really try to stay simple. Recent conversations in uv showed that users have many different needs, and it's likely more the job of the package installer to provide different resolution methods rather than the server's job.

For example, uv now supports this:

> `UV_INDEX_STRATEGY`: Equivalent to the `--index-strategy` command-line argument. For example, if set to `unsafe-any-match`, uv will consider versions of a given package available across all index URLs, rather than limiting its search to the first index URL that contains the package.

When using uv you can therefore stop relying on the fallback mechanism and just tell uv to search in both your private index and PyPI.org.

However I understand that a package server would prefer to work well with any package installer :thinking: 

Maybe the best thing pypiserver can do is work on supporting [PEP 708](https://peps.python.org/pep-0708/), which goes in that direction. If maintainers think it's the best route, I'd suggest closing this issue and opening a new one to support PEP 708 :slightly_smiling_face:
