### ISSUE TITLE
Update 404 return to match PyPI

### ISSUE THREAD

**Issue by MikeSchneeberger** [pypiserver/pypiserver#180]
When disabling the fallback ...

`pypi-server --disable-fallback -p 8080 -P C:\Data\htpasswd C:\Data\packages`

... I get the following exception, when trying to install a package that doesn't exists on the pypi server.

```
(C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv) C:\Users\[USER]\Documents>pip install paramiko2
Collecting paramiko2
Exception:
Traceback (most recent call last):
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\pip\index.py", line 795, in get_page
    resp.raise_for_status()
  File "C:\Users\[USER]\AppData\Local\Continuum\anaconda3\envs\venv\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
pip._vendor.requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://[IP OF PYPI SERVER]/simple/paramiko2/
```

I notices that doing the same on pypi.python.com in the browser (https://pypi.python.org/simple/paramiko2/), I get ...

`Not Found (paramiko2 does not exist)`

... the same with the pypi server (http://[IP OF PYPI SERVER]:8080/simple/paramiko2/) gives me a HTTP-Error message.

```
Error: 404 Not Found

Sorry, the requested URL 'http://[IP OF PYPI SERVER]:8080/simple/paramiko2/' caused an error:
```

**Comment by mplanchard** [comment]
This is expected. If you do not have the package and fallback is disabled, we return a 404 (Not Found). It is interesting that PyPI is apparently returning something a little different for the 404, which is why `pip` is able to give you a nice `does not exist` message rather than a 404 error.

Is this difference problematic for you?

**Comment by mplanchard** [comment]
Looked into this briefly, and here's the difference between the two returns:

## PyPI

```
In [2]: r = requests.get('http://pypi.python.org/simple/paramiko2/')

In [4]: r.status_code
Out[4]: 404

In [5]: r.text
Out[5]: 'Not Found (paramiko2 does not exist)\n\n'
```

## PyPIServer

```
In [6]: r = requests.get('http://localhost:8080/simple/paramiko2/')

In [7]: r.status_code
Out[7]: 404

In [8]: r.text
Out[8]: '\n    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n    <html>\n        <head>\n            <title>Error: 404 Not Found</title>\n            <style type="text/css">\n              html {background-color: #eee; font-family: sans-serif;}\n              body {background-color: #fff; border: 1px solid #ddd;\n                    padding: 15px; margin: 15px;}\n              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}\n            </style>\n        </head>\n        <body>\n            <h1>Error: 404 Not Found</h1>\n            <p>Sorry, the requested URL <tt>&#039;http://localhost:8080/simple/paramiko2/&#039;</tt>\n               caused an error:</p>\n            <pre></pre>\n        </body>\n    </html>\n'
```

Seems like pip is just returning whatever the URL returns. It would be pretty easy to adjust ours to match.
