### ISSUE TITLE
pypiserver does not get along with pip search 

### ISSUE THREAD

**Issue by jkpubsrc** [pypiserver/pypiserver#181]
Description:

I tried to configure pip to search a local server. Therefore I added "index" and "index-url" parameters to the global section of /etc/pip.conf . Unfortunately if I do that pip3 seems to fail as the pypiserver does not deliver data as pip would expect it:

```
$ pip -v search asdklalsjdalksd
Starting new HTTP connection (1): 192.168.10.11
"POST / HTTP/1.1" 400 745
HTTP error 400 while getting http://192.168.10.11/
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/search.py", line 45, in run
    pypi_hits = self.search(query, options)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/search.py", line 62, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.5/dist-packages/pip/download.py", line 776, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
pip._vendor.requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.10.11/
```

In contrast the correct response by pip if I disable the local repository:

```
$ pip3 -v search asdklalsjdalksd
Starting new HTTPS connection (1): pypi.python.org
"POST /pypi HTTP/1.1" 200 None
```

Operating system used: Ubuntu 16.04
Latest pip, default python3.

**Comment by ankostis** [comment]
*Pypiserver*, by design, does not perform any requests downstream, And this is required for search to work for missing packages, when you specify `index` and `index-url` in your `pip.conf`.

That is why the [client-side-configurations](https://github.com/pypiserver/pypiserver#client-side-) we recommend to use the `extra-index-url` option.  That way, any missing packages are delegated by *your `pip`, locally* to the central PyPi repo.

If this behavior does not fit your needs, then better use [some other server](https://github.com/pypiserver/pypiserver#similar-projects).

**Comment by jkpubsrc** [comment]
I'm very sorry, but I don't understand. Pypiserver hosts a variety of packages. That's what it is designed for. I assume if pip tries to perform a a search it downloads the package index from a pypiserver instance and then filters the list. After that - I assume - it will provide the results to the user. That does not seem to work. Please correct me if I'm wrong but exactly I don't understand where in this architecture I'm assuming here some kind of "downstream" could have it's place. If pip does not follow some weird design the pypiserver should just need to present the package list to pip and everything should be fine. It serves a list of packages anyway. But I didn't design pip, so you will likely know much more about its peculiarities. Could you provide me with a bit more information regarding that problem? Thank you!

Regarding pip: I configured pip to ONLY serve packages from a pypiserver instance. Then searching failed as pip now queried my local installation of pypiserver and not the official PyPi repository.

And I really hope that in the long run the developers of pip provide better ways to define from what servers to retrieve packages. As anyone can submit to the PyPi repository it is a security risk that local repositories are "extra" and don't come first in the internal search order for packages. What's even worse is that pip does not provide information from where exactly it downloads a package. But that's a different kind of a story, a problem of pip, not of pypiserver.

And - by the way - I very much like your pypiserver! I intend to use it for many years in the future if you don't mind :-)

**Comment by ankostis** [comment]
Don't get me wrong, there was no pun intended about other projects; at all.  

Additionally, I misunderstood you report in the first place, so had already edited my previous answer, writting that indeed a bug might lurk somewehere.

> Regarding pip: I configured pip to ONLY serve packages from a pypiserver instance. Then searching failed as pip now queried my local installation of pypiserver and not the official PyPi repository.

If that is exactly what you want, then it fits your needs perfectly :-)

Btw, have you checked #170?

**Comment by mplanchard** [comment]
Thanks for the report! If this is indeed a bug,  the following would help us in trying to pin down the cause:

* pip config, with any sensitive information redacted
* output from `pip --version`
* output from `pypi-server --version`
* command-line invocation of pypiserver used to reproduce the problem
* Any `stdout` or `stderr` that shows up when the pypiserver is run in the foreground and the request is repeated

Does the error occur both for packages that do not exist in your repository, such as `asdklalsjdalksd`, as well as for packages that are being served by pypiserver? 

Pip has been doing quite a bit of modernization/updating of their protocols recently, so I would not be super surprised if they have changed something about the search API!

**Comment by smekkley** [comment]
For me, pip search works across many python/pip version, even with the latest pip version.
The only difference I noticed is that it's pretty strict. Like uppercase packages cannot be found by lower case search. I think it's also strict on underscore/dash. I'm not sure if it's worth creating a new issue.

We also want to watch out for this issue. Maybe xmlrpc will be gone in the future.
https://github.com/pypa/pip/issues/395
