### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by hscspring** [pypiserver/pypiserver#199]
I use TencentCloud for my server, and i use docker, when i finished the construction, i got a log like below ( the server is ok), is anyone met the same issue?  

```
[pypi]----------------------------------------
[pypi]----------------------------------------
[pypi]Exception happened during processing of request from ('172.21.0.6', 29758)
[pypi]Traceback (most recent call last):
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
[pypi] self.process_request(request, client_address)
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 348, in process_request
[pypi] self.finish_request(request, client_address)
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
[pypi] self.RequestHandlerClass(request, client_address, self)
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
[pypi] self.handle()
[pypi] File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 118, in handle
[pypi] self.raw_requestline = self.rfile.readline(65537)
[pypi] File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
[pypi] return self._sock.recv_into(b)
[pypi]ConnectionResetError: [Errno 104] Connection reset by peer
[pypi]----------------------------------------
[pypi]----------------------------------------
[pypi]Exception happened during processing of request from ('172.16.4.1', 32684)
[pypi]Traceback (most recent call last):
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
[pypi] self.process_request(request, client_address)
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 348, in process_request
[pypi] self.finish_request(request, client_address)
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
[pypi] self.RequestHandlerClass(request, client_address, self)
[pypi] File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
[pypi] self.handle()
[pypi] File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 118, in handle
[pypi] self.raw_requestline = self.rfile.readline(65537)
[pypi] File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
[pypi] return self._sock.recv_into(b)
[pypi]ConnectionResetError: [Errno 104] Connection reset by peer
```

The dockerfile is:  

```
FROM ccr.ccs.tencentyun.com/ai-hub/python-3.6.3

# Build

RUN pip install pypiserver
RUN pip install passlib

# Data Directory
RUN mkdir -p /data/packages
RUN mkdir -p /config

ADD htpasswd.txt /config/.htaccess

WORKDIR /data

ENTRYPOINT ["pypi-server", "-P", "/config/.htaccess"]
CMD ["-p", "3141", "packages"]
EXPOSE 3141
```

**Comment by pawamoy** [comment]
I'd suggest closing old issues like this one, unless someone can provide a minimal reproduction example that reproduces the issue with recent versions of pypiserver.
