### ISSUE TITLE
Import error on starting pypiserver

### ISSUE THREAD

**Issue by rhuab** [pypiserver/pypiserver#207]
I execute the command "pypi-server -p 9090 modules" but get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/pypi-server", line 7, in <module>
    from pypi_server.server import run
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/server.py", line 20, in <module>
    from pypi_server.handlers.pypi.proxy.client import PYPIClient
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/handlers/__init__.py", line 44, in <module>
    import pypi_server.handlers.pypi
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/handlers/pypi/__init__.py", line 2, in <module>
    from pypi_server.handlers.pypi import simple
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/handlers/pypi/simple/__init__.py", line 2, in <module>
    from pypi_server.handlers.pypi.simple.packages import PackagesHandler
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/handlers/pypi/simple/packages.py", line 9, in <module>
    from pypi_server.db.packages import Package, PackageVersion, PackageFile
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/db/__init__.py", line 17, in <module>
    from .migrator.model import Migrations
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/db/migrator/__init__.py", line 22, in <module>
    import pypi_server.db.migrator.migrations
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/db/migrator/migrations/__init__.py", line 32, in <module>
    sys.modules["{}.{}".format(__name__, mod.name)] = imp.load_source(mod.name, mod.path)
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/db/migrator/migrations/001_create_tables.py", line 3, in <module>
    from pypi_server.db.users import Users
  File "/usr/local/lib/python2.7/dist-packages/pypi_server/db/users.py", line 5, in <module>
    from playhouse.fields import gensalt, hashpw
ImportError: cannot import name gensalt
```
I tried to install pypiserver on both python3.6 and python2.7 but doesn't work.

**Comment by mplanchard** [comment]
Hi there, and thanks for reporting this. 

I think you’ve got the wrong package installed. Your traceback shows that the installed package is called `pypi_server` but this project is called `pypiserver` (although the executable is `pypi-server` and maybe this shows that it should be changed). 

Try `pip uninstall pypi-server && pip install pypiserver` and then see if things work as expected.

**Comment by rhuab** [comment]
It works, thx for help!

**Comment by mplanchard** [comment]
You’re welcome! Glad it was something easy to fix 😁

I’m going to mark this as resolved, but feel free to open a new issue if you run into any more problems.
