### ISSUE TITLE
Socket error while installing packages

### ISSUE THREAD

**Issue by elboerto** [pypiserver/pypiserver#221]
I'm getting this errors in my pypiserver logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/local/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
192.168.1.43 - - [18/Sep/2018 14:18:34] "GET /packages/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('192.168.1.43', 53848)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/usr/local/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 133, in handle
    handler.run(self.server.get_app())
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/local/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```
On the client side I get:

```
toolBackend_1   | Collecting *** (from -r /source/ToolRuntime/requirements.txt (line 1))
toolBackend_1   |   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPConnection object a
t 0x7faa066fe7b8>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/***/
```

Can someone help me to track down this error?
Thanks! :)

**Comment by mplanchard** [comment]
Hmm, this is an interesting one. Could you include some information about the server environment (OS, python version, pypiserver version, command-line args, etc.)?

Setting pypiserver to debug (passing `-vvv` on the commandline) and getting the server output might also be helpful

**Comment by elboerto** [comment]
I could solve this error by changing the WSGI Server from default to paste by
`pypiserver --server paste`
so this might be a bug in the wsgiref implementation.

It was very hard to replicate this error because it occured infrequently and only under load situations (downloading 20 packages from 2 clients). I don't know if I have time to replicate it with the -vvv argument in the next weeks.

Python: 3.6.5
OS: Debian jessie
Pypiserver: 1.2.4 (no command line arguments except port and package folder)
