### ISSUE TITLE
pypi-uploader project seems to be dead

### ISSUE THREAD

**Issue by willrogers** [pypiserver/pypiserver#241]
The documentation describes using `pypiupload` to upload packages. However, when I tried to do this I got the following error:

```
$ pypiupload packages chardet==3.0.2 -i local
Traceback (most recent call last):
  File "/home/hgs15624/code/python/pytac/venv/bin/pypiupload", line 10, in <module>
    sys.exit(main())
  File "/home/hgs15624/code/python/pytac/venv/lib/python2.7/site-packages/pypiuploader/commands.py", line 40, in main
    command.run()
  File "/home/hgs15624/code/python/pytac/venv/lib/python2.7/site-packages/pypiuploader/commands.py", line 91, in run
    filenames = self._get_filenames()
  File "/home/hgs15624/code/python/pytac/venv/lib/python2.7/site-packages/pypiuploader/commands.py", line 101, in _get_filenames
    filenames = self._download()
  File "/home/hgs15624/code/python/pytac/venv/lib/python2.7/site-packages/pypiuploader/commands.py", line 111, in _download
    no_use_wheel=self.options.no_use_wheel)
  File "/home/hgs15624/code/python/pytac/venv/lib/python2.7/site-packages/pypiuploader/download.py", line 72, in download
    pip.main(args)
AttributeError: 'module' object has no attribute 'main'
```

When I looked up the project, I found that its Github page has disappeared: https://github.com/ignacysokolowski/pypi-uploader

**Comment by mplanchard** [comment]
Oh dear! I'll remove that bit from the docs. I'd recommend using `twine` instead.
