### ISSUE TITLE
Not work at 80 port

### ISSUE THREAD

**Issue by bizlevel** [pypiserver/pypiserver#244]
I have Fresh Debian 9 stretch and run next:
```
sudo apt-get install python-setuptools apache2-utils
sudo easy_install pip
sudo pip install pypiserver passlib
sudo mkdir /opt/packages
sudo chmod 777 /opt/packages
sudo touch /var/log/pypiserver.log
sudo chmod 666 /var/log/pypiserver.log
```

After that i run:
`pypi-server -p 8080 -a update,download --log-file /var/log/pypiserver.log -P /opt/htpasswd.txt /opt/packages`

And all is fine.
But if i run:
`pypi-server -p 80 -a update,download --log-file /var/log/pypiserver.log -P /opt/htpasswd.txt /opt/packages`

I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/pypi-server", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/__main__.py", line 294, in main
    bottle.run(app=app, host=c.host, port=c.port, server=c.server)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 3270, in run
    server.run(app)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 3106, in run
    return sa(self.host, self.port, **self.options).run(handler)
  File "/usr/local/lib/python2.7/dist-packages/pypiserver/bottle.py", line 2840, in run
    handler_cls)
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 151, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 13] Permission denied
```

But no any service on 80 port are listener, i rechecked it by netstat.
What is wrong?

**Comment by bizlevel** [comment]
We found solutions.
Need root right to run app on 80 port, or guid < 1000
