### ISSUE TITLE
Permission issues when using existing packages folder with Docker setup

### ISSUE THREAD

**Issue by a-recknagel** [pypiserver/pypiserver#256]
### How to reproduce
```bash
mdkir packages
docker run -d -p 8080:8080 -v ~/tmp/pypiserver/packages:/data/packages pypiserver/pypiserver:latest
twine upload --repository-url http://0.0.0.0:8080 my/local/package.whl
```
### Server logs
```
172.17.0.1 - - [29/May/2019 06:48:04] "POST / HTTP/1.1" 500 745
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pypiserver/bottle.py", line 923, in _handle
    return route.call(**args)
  File "build/bdist.linux-x86_64/egg/pypiserver/bottle.py", line 1845, in wrapper
    rv = callback(*a, **ka)
  File "build/bdist.linux-x86_64/egg/pypiserver/_app.py", line 52, in protector
    return method(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pypiserver/_app.py", line 195, in update
    file_upload()
  File "build/bdist.linux-x86_64/egg/pypiserver/_app.py", line 172, in file_upload
    core.store(packages.root, uf.raw_filename, uf.save)
  File "build/bdist.linux-x86_64/egg/pypiserver/core.py", line 283, in store
    save_method(dest_fn, overwrite=True)  # Overwite check earlier.
  File "build/bdist.linux-x86_64/egg/pypiserver/bottle.py", line 2447, in save
    with open(destination, 'wb') as fp:
IOError: [Errno 13] Permission denied: '/data/packages/package.whl'
```
### Workaround

```bash
mdkir packages
chown -R 9898:98989 packages  # the internal user id can be looked up in the Dockerfile
docker run -d -p 8080:8080 -v ~/tmp/pypiserver/packages:/data/packages pypiserver/pypiserver:latest
twine upload --repository-url http://0.0.0.0:8080 my/local/package.whl
```
Doing this seems like a hack, and is not documented in [the section on docker deployments](https://pypi.org/project/pypiserver/#using-the-docker-image). Am I doing something wrong?

**Comment by mplanchard** [comment]
Hm. I'm sorry you're getting this error!

I didn't have to do this locally when I was testing out the docker deployments. Could you give me a bit more information about the system you're running on?

Once we get the root cause figured out, I'll either update the docs to make things clearer or update the docker config to make it easier.

Totally agree with your use-case, and that was indeed our intention with putting those docs front-and-center, because I figured mounting a local directory would be a pretty common desire.

**Comment by a-recknagel** [comment]
Hi @mplanchard, thanks for checking in this.

It seems I trashed that environment, so it took me a while to rebuild a good test case.
My system:
```bash
docker --version
Docker version 18.09.6, build 481bc77
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

What I ran:
```bash
git clone https://github.com/pypiserver/pypiserver.git
cd pypiserver
mkdir packages
sed -i '19i    -v "${DIR}/packages:/data/packages" \\' bin/test-docker.sh
./bin/test-docker.sh
```

This will result in the error that I described, which will be visible in the docker logs.

**Comment by fwkz** [comment]
Same issue here. 👋

**Comment by mplanchard** [comment]
Thanks for the reproduction and reports! Sorry it's taken so long to get to this.

So the reason this is happening is because the `pypiserver` Dockerfile manually specifies a UID and GID for the `pypiserver` user and group, respectively. The reason for this is for security. There is no reason for the `pypi-server` instance within the container to run as `root`. See [here](https://docs.docker.com/v17.12/engine/security/userns-remap/), [here](https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf), and [here](https://dev.to/nownabe/secure-user-in-docker-1b5m) for details.

Adding a `pypiserver` user in the Docker container prevents running as root, and giving it a unique ID prevents it from running with the host user's permissions, as well, allowing users to be more granular in what permissions the container has. 

I think the reason I haven't seen the issue with local mounts before is that the Docker daemon runs differently on Linux compared to Mac (see the second link above). On my local machine, running `docker run --entrypoint /bin/sh -it -v $(pwd)/packages:/data/packages pypiserver/pypiserver:latest` gets me into a shell where I can verify with `ls -al` that the `packages` directory is owned by `pypiserver:pypiserver`.

However, I _am_ able to replicate this on a local Kubuntu VM, where doing the same as above shows me a `packages` directory owned by my local user ID (1000), and in which the pypiserver user is not allowed to write files via `touch`!

I've verified the three potential workarounds below, which I agree we should document better for our Linux users:

* Run as the root user in the container using the `--user 0` argument to `docker run` or a similar config in `docker-compose`. **This is not recommended, because it allows the container to run commands as the host root.**
* Run as your local user ID in the container using something like `--user $(id -u $(whoami))`. This is better, but still gives the container more privileges than it needs.
* Adjusting the ownership of the `packages` directory to add the known GID of the `pypiserver` group (9898). The nicest way to do this is probably to also add a `pypiserver` group locally, b/c it makes it very clear what's going on re: ownership and permissions:
  ```
  sudo groupadd -g 9898 pypiserver
  sudo chgrp -R pypiserver packages
  ```
  At this point, logging into the container as mentioned above shows the `packages` directory to be correctly owned by the `pypiserver` group, and I am able to `touch` files within. This is probably the best approach, although involves a few more steps.
* Entirely adjusting the ownership of the directory, as in your workaround listed in the initial issue.

**Comment by asabbagh** [comment]
> four potential workarounds

- Can you clarify where the 2 commands in option 3 would be executed? Inside the docker container, or on the host? Do you need to also create a user, or will the group suffice?
- What is the difference between option 3 and option 4? I thought option 3 was also "adjusting the ownerhsip of the directory". Or are you referring to the `98989` (in which case I believe that might just have been a typo in the original comment).

**Comment by mplanchard** [comment]
> Can you clarify where the 2 commands in option 3 would be executed? Inside the docker container, or on the host? Do you need to also create a user, or will the group suffice?

These would need to be run on the host. 

The issue is that the `package` directory being mounted in the container retains the same UID/GID settings as on the host. So if your host user is user 1000, and your user owns the `packages` directory, it'll still be owned by user 1000 inside the docker container, even though that user does not exist. You do not need to create the user, because the `pypiserver` user in the Docker container is a member of the `pypiserver` group, so as long as the correct GID has access to the directory, you're good to go.

> What is the difference between option 3 and option 4? I thought option 3 was also "adjusting the ownerhsip of the directory". Or are you referring to the 98989 (in which case I believe that might just have been a typo in the original comment

Sorry, I was not super explicit in the way I originally stated that. Option 4 would be changing the user AND group for the directory with `chown`, so that your host user no longer owns the directory at all.

**Comment by minamaged113** [comment]
I have faced the problem when my docker volume, which was used by another container, got attached to the server.
However, I have created a new docker volume and attached it to PyPIserver and it worked.
