### ISSUE TITLE
ValueError: malformed htpasswd file when use helm to install pypiserver

### ISSUE THREAD

**Issue by HenrryVargas** [pypiserver/pypiserver#282]
I am using pypiserver chart to install it in kubernetes.

**I have in the values.yaml:**

```yaml
auth:
  ## comma-separated list of (case-insensitive) actions to authenticate
  ## Use '.' or '' for empty. Requires to have set the password (option below).
  ## Available actions are update, download and list
  actions: update,download,list
  ## List of username / encoded passwords that will be put to the htpasswd file
  ## use `htpasswd -n -b username password` to generate them

  credentials: {pepe:$apr1$9RZcghjr$MxxlAK/Iv0cVRhtzOegQp0}
```

**I have  in the deployment.yaml:**

```yaml
containers:
        - name: {{ template "pypiserver.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["pypi-server"]
          args:
            - --passwords=/config/.htpasswd            
            - --authenticate={{ .Values.auth.actions }}
            - --port=8080
            {{- range .Values.pypiserver.extraArgs }}
            - {{ . }}
            {{- end }}
            - /data/packages
```

**message from pod:**

```
Traceback (most recent call last):
  File "/usr/bin/pypi-server", line 11, in <module>
    load_entry_point('pypiserver==1.3.0', 'console_scripts', 'pypi-server')()
  File "build/bdist.linux-x86_64/egg/pypiserver/__main__.py", line 293, in main
  File "build/bdist.linux-x86_64/egg/pypiserver/__init__.py", line 131, in app
  File "build/bdist.linux-x86_64/egg/pypiserver/core.py", line 54, in configure
  File "/tmp/pip-install-cKFicM/passlib/passlib/apache.py", line 721, in __init__
  File "/tmp/pip-install-cKFicM/passlib/passlib/apache.py", line 140, in __init__
  File "/tmp/pip-install-cKFicM/passlib/passlib/apache.py", line 214, in load
  File "/tmp/pip-install-cKFicM/passlib/passlib/apache.py", line 242, in _load_lines
  File "/tmp/pip-install-cKFicM/passlib/passlib/apache.py", line 728, in _parse_record
**ValueError: malformed htpasswd file (error reading line 1)**
```

**Comment by mplanchard** [comment]
It looks like this error is being raised directly from the `passlib` library. I'd recommend using the [htapasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) command directly to verify your `htpasswd` file. If you're configuring your server to use an `htpasswd` file, and `passlib` cannot parse it, there's not much we can do other than raise the error.

**Comment by mekza** [comment]
@HenrryVargas there is a missing space after `:` in your credentials map.

```yaml
auth:
  ## comma-separated list of (case-insensitive) actions to authenticate
  ## Use '.' or '' for empty. Requires to have set the password (option below).
  ## Available actions are update, download and list
  actions: update,download,list
  ## List of username / encoded passwords that will be put to the htpasswd file
  ## use `htpasswd -n -b username password` to generate them

  credentials: {pepe: $apr1$9RZcghjr$MxxlAK/Iv0cVRhtzOegQp0}
```
