### ISSUE TITLE
Command "pypi-server -U" crashes with error HTTPTooManyRequests

### ISSUE THREAD

**Issue by nikoluis** [pypiserver/pypiserver#388]
Recently I setup pypi-server on a VM with windows 10 and i have setup all of my Raspberry PIs to have their pip download from this machine. Since i operate on a large scale organization, my only solution to have newest packages, is through a local pypi-server that connects to internet. It works fine, i installed it as a windows service. Today I wanted to download the latest versions of my packages (around 120 packages) so i used pypi-server -U c:\MY_PACKAGES, but i got the following error and any help would be appreciated:

checking 115 packages for newer version

.Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\pypi-server.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\pypiserver\__main__.py", line 310, in main
    update_all_packages(
  File "c:\program files\python39\lib\site-packages\pypiserver\manage.py", line 214, in update_all_packages
    update(packages, destdir, dry_run, stable_only)
  File "c:\program files\python39\lib\site-packages\pypiserver\manage.py", line 198, in update
    need_update = find_updates(pkgset, stable_only=stable_only)
  File "c:\program files\python39\lib\site-packages\pypiserver\manage.py", line 120, in find_updates
    pypi_versions = pypi.package_releases(pkg.pkgname)
  File "c:\program files\python39\lib\xmlrpc\client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "c:\program files\python39\lib\xmlrpc\client.py", line 1458, in __request
    response = self.__transport.request(
  File "c:\program files\python39\lib\xmlrpc\client.py", line 1160, in request
    return self.single_request(host, handler, request_body, verbose)
  File "c:\program files\python39\lib\xmlrpc\client.py", line 1176, in single_request
    return self.parse_response(resp)
  File "c:\program files\python39\lib\xmlrpc\client.py", line 1348, in parse_response
    return u.close()
  File "c:\program files\python39\lib\xmlrpc\client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: 'HTTPTooManyRequests: The action could not be performed because there were too many requests by the client. Limit may reset in 1 seconds.'>

**Comment by mplanchard** [comment]
This is an interesting one, thanks for raising it! The update command works by querying PyPI for new versions of the packages. Looks like they've got some rate-limiting going on. We don't currently have anything in place to deal with this via a backoff or anything like that. That's something I would like to add, but I don't have the time to commit to it at the moment.

In the meantime, the only thing I can think of would be to do it in groups by moving some packages out of the package directory, running the upload command, and then repeating that process with the remaining packages. 

Alternatively, you could clone this repo locally and add a `time.sleep(10)` or something after this line: https://github.com/pypiserver/pypiserver/blob/35fcdd0e061e783058634a54de135174e57f2771/pypiserver/manage.py#L84

Then build the package with `pip install -e .` in a virtual environment, and use that to update the packages.

**Comment by nikoluis** [comment]
I cloned the repo, added the line you suggested and it worked! However, sleep(10) was too much:) and sleep(1) was causing the same error after a few seconds. But sleep(2) did the job. Thanks for the tip.
