### ISSUE TITLE
pip + pypiserver asks for username when executing `pip search`

### ISSUE THREAD

**Issue by itsayellow** [pypiserver/pypiserver#390]
I'm using pypiserver on my local machine and tried `pip search` with it as instructed in the pypiserver directions.

However, it asks for a username, which I didn't configure with pypiserver (and which the pypiserver instructions don't mention for `pip search`.)  On the pypiserver log it indicates a POST is being executed when I do a `pip search`.

Is this a bug or something I'm doing wrong?

macOS 11.3
python3 3.9.4
pypiserver v1.4.2
pip v21.0.1

Running pypiserver:
```shell
> pypi-server packages   
127.0.0.1 - - [29/Apr/2021 13:04:57] "POST / HTTP/1.1" 401 706
```

pip execution:
```shell
> pip search --index http://localhost:8080/ pipx
User for localhost:8080: 
```

**Comment by dee-me-tree-or-love** [comment]
Hey @itsayellow, thanks a lot for reporting this! Very sorry for responding so late. I've checked it locally and it indeed seems like an existing issue. I will dive deeper to try finding a cause/solution and will get back to you here.

**Comment by dee-me-tree-or-love** [comment]
Hi @itsayellow, sorry for a long silence! It's been a while now I've been afk for this project, but I did a couple of quick tests for your problem. Although I haven't found a solution yet, I found a few interesting ques that might lead to something. Do you still experience the issue or maybe managed to get it solved? Will be happy to hear your updates! 

So what I found: 

1. The `list` endpoint used for search is indeed protected with basic auth in pypiserver, same approach as used for downloads. Maybe that helps 🤔.
2. Search functionality generally is being deprecated in `pip` - https://github.com/pypa/pip/issues/5216 (related to discussions here) + https://status.python.org/, which is interesting. 
3. I have tried running the same command against `pypiserver` and indeed stumble upon the same issue as you describe, and then I've looked at the verbose output with `-vvv` and noticed that the error comes in from within `pip`'s implementation. In `Pypa/pip` it's raised in `auth.py` `handle_401`.
    - More detailed, check `Pypa/pip/_internal/network/auth.py:L223` for password prompt which is caused at `Pypa/pip/_internal/network/auth.py:L263` if no credentials from `keyring` (in my case) were found. I feel it might actually have to do something with adding trusted network locations and their username/password combinations to the keyring or maybe specifying the user password pair as basic auth in the URL used for `--index` parameter. Some (seems like) related items here: https://github.com/pypa/pip/issues/4315, https://github.com/pypa/pip/issues/51.  

This is the output:

```bash
$ python3 -m pip search --index http://localhost:8080/ pipx -vvv --trusted-host localhost:8080
Starting new HTTP connection (1): localhost:8080
http://localhost:8080 "POST / HTTP/1.1" 401 706
Getting credentials from keyring for localhost:8080
Loading KWallet
Loading SecretService
Loading Windows
Loading chainer
Loading macOS
User for localhost:8080: ^CERROR: Operation cancelled by user
Exception information:
Traceback (most recent call last):
  File "...lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 173, in _main
    status = self.run(options, args)
  File "...lib/python3.8/site-packages/pip/_internal/commands/search.py", line 54, in run
    pypi_hits = self.search(query, options)
  File "...lib/python3.8/site-packages/pip/_internal/commands/search.py", line 74, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "...lib/python3.8/site-packages/pip/_internal/network/xmlrpc.py", line 44, in request
    response = self._session.post(
  File "...lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "...lib/python3.8/site-packages/pip/_internal/network/session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "...lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "...lib/python3.8/site-packages/pip/_vendor/requests/sessions.py", line 662, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "...lib/python3.8/site-packages/pip/_vendor/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "...lib/python3.8/site-packages/pip/_internal/network/auth.py", line 263, in handle_401
    username, password, save = self._prompt_for_password(parsed.netloc)
  File "...lib/python3.8/site-packages/pip/_internal/network/auth.py", line 226, in _prompt_for_password
    username = ask_input(f"User for {netloc}: ")
  File "...lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 218, in ask_input
    return input(message)
KeyboardInterrupt
```

---

Sorry I couldn't look into it even more recently, but maybe that helps out in some way? 
Let me know if you try something out or get a solution. I will try to look into it closer sometime soon again ✌️ Really sorry it's taking so long!
