### ISSUE TITLE
BrokenPipeError after code 400

### ISSUE THREAD

**Issue by mislavk** [pypiserver/pypiserver#402]
I'm getting [Errno 32] Broken pipe after message Bad request type. 
I'm using docker-compose for pypiserver and jenkins as a client. Jenkins uses virtual environment for pip (installed through requierments file). It mostly works perfectly, but then this error happens. It mostly happens at night and in the morning.

Below is a docker container log:
```
192.168.1.27 - - [27/Sep/2021 16:34:16] code 400, message Bad HTTP/0.9 request type ('Z¥\x01')
192.168.1.27 - - [27/Sep/2021 16:34:16] "Z¥ " 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.27', 56316)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/wsgiref/simple_server.py", line 126, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/local/lib/python3.8/http/server.py", line 329, in parse_request
    self.send_error(
  File "/usr/local/lib/python3.8/http/server.py", line 482, in send_error
    self.wfile.write(body)
  File "/usr/local/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```
Here's another example:
```
192.168.1.29 - - [24/Sep/2021 15:17:53] code 400, message Bad request syntax ('\x04\x01\x00P²\x80"c0\x00')
192.168.1.29 - - [24/Sep/2021 15:17:53] "P²"c0" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.29', 41049)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/wsgiref/simple_server.py", line 126, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/local/lib/python3.8/http/server.py", line 321, in parse_request
    self.send_error(
  File "/usr/local/lib/python3.8/http/server.py", line 482, in send_error
    self.wfile.write(body)
  File "/usr/local/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```
Here is docker-compose config:
```
version: '3.7'

services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    ports:
      - 8000:8080
    volumes:
      - type: bind
        source: {bind_source_path}
        target: {bind_target_path}
      - type: volume
        source: pypi-server
        target: {volume_target_path}
    command: -P {bind_target_path}/.htpasswd -a update,download,list {volume_target_path}
    restart: always

volumes:
  pypi-server:
```
And jenkins pip config:
```
[global]
index = http://{{pypi_username}}:{{pypi_password}}@{{pypi_url}}:{{pypi_port}}/pypi
index-url = http://{{pypi_username}}:{{pypi_password}}@{{pypi_url}}:{{pypi_port}}/simple
trusted-host = {{pypi_url}}
```

Can anyone help me with the error? Thanks!

**Comment by dee-me-tree-or-love** [comment]
Hi @mislavk, thanks for raising this issue! I have also spotted some strange behaviour in the tests running in CI that seems to might be related. Could you provide any more details about what kind of behaviour / actions are taken prior to those errors (at night and morning)? Are there any specific calls and if yes, then to which endpoint?  

I will try to investigate when time allows, but I can't promise any timing as I am a bit busy these days with my main work and studies at the moment. So all helping hands are especially welcome.

**Comment by dee-me-tree-or-love** [comment]
Hey @mislavk, no worries about it, my apologies for an even later reaction here. I have not yet seen a similar behaviour here actually yet. For some reason, the issues disappeared recently without me really having a chance to properly investigate or identify the underlying problems. Maybe it was mostly network issues at that point on our end but remains interesting.  

Are you experiencing those problems still? 
I would be happy to hear some updates if you manage to find something. I will continue paying attention too, and will report if I will be able to spot anything useful.

**Comment by mislavk** [comment]
Hi @dee-me-tree-or-love since I changed to cherrypy web server I haven't seen any weird behaviour, everything works perfectly.

**Comment by dee-me-tree-or-love** [comment]
Hi @mislavk, that's great to hear, thanks a lot for the update! If it looks stable now and it's okay, I will close the issue, but feel free to reopen it if anything. ✌️
