### ISSUE TITLE
Bottle missing gevent monkey patch

### ISSUE THREAD

**Issue by doismellburning** [pypiserver/pypiserver#49]
Currently, attempting to run `pypiserver` with `--server gevent` fails due to lack of a monkey patch call:

```
$ pip freeze | grep pypiserver
pypiserver==1.1.6
$ pip freeze | grep gevent
gevent==1.0
$ pypi-server --server gevent -P htpasswd goat/
This is pypiserver 1.1.6 serving '/home/vagrant/goat' on http://0.0.0.0:8080

Bottle v0.11.6 server starting up (using GeventServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/home/vagrant/.env/bin/pypi-server", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.env/local/lib/python2.7/site-packages/pypiserver/core.py", line 328, in main
    run(app=a, host=host, port=port, server=server)
  File "/home/vagrant/.env/local/lib/python2.7/site-packages/pypiserver/bottle.py", line 2703, in run
    server.run(app)
  File "/home/vagrant/.env/local/lib/python2.7/site-packages/pypiserver/bottle.py", line 2499, in run
    raise RuntimeError(msg)
RuntimeError: Bottle requires gevent.monkey.patch_all() (before import)
```

**Comment by ankostis** [comment]
@doismellburning Would you mind checking if my branch fixed it?

**Comment by doismellburning** [comment]
```
(.env)[2015-03-15T12:08:43+0000 ~/pypiserver] (detached from fcf6f4c) $ pip freeze
You are using pip version 6.0.6, however version 6.0.8 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
gevent==1.0.1
greenlet==0.4.5
passlib==1.6.2
-e git+git@github.com:pypiserver/pypiserver.git@fcf6f4c6153fe50d0b956e668c02d1fe6ea2af72#egg=pypiserver-ankostis_gevent
(.env)[2015-03-15T12:08:41+0000 ~/pypiserver] (detached from fcf6f4c) $ ./pypi-server --server gevent -P htpasswd .
Bottle v0.11.6 server starting up (using GeventServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "./pypi-server", line 5, in <module>
    main()
  File "/home/vagrant/pypiserver/pypiserver/core.py", line 454, in main
    run_bottle_server(app=a, host=host, port=port, server=server, roots=roots)
  File "/home/vagrant/pypiserver/pypiserver/core.py", line 312, in run_bottle_server
    bottle.run(app=app, host=host, port=port, server=server)
  File "/home/vagrant/pypiserver/pypiserver/bottle.py", line 2703, in run
    server.run(app)
  File "/home/vagrant/pypiserver/pypiserver/bottle.py", line 2499, in run
    raise RuntimeError(msg)
RuntimeError: Bottle requires gevent.monkey.patch_all() (before import)
Exception KeyError: KeyError(4524746704,) in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
```

Alas no - did you experience success yourself?

**Comment by ankostis** [comment]
Me neither.

**Comment by ankostis** [comment]
I think i nailed it.  It was invoking app() before monkey-patch.
@doismellburning  can you please try with latest commit?

Test-case pending.

**Comment by ankostis** [comment]
Tested on linux (`gevent` under *Windows* is still experintal) and it seems to work.

**Comment by ankostis** [comment]
Postponed.

Better restructure startup-sequence and  update testing fictures.  Them this will be trivial to fix.
