### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by Moggele** [pypiserver/pypiserver#629]
Using the Docker image pypiserver/pypiserver   latest

Traceback (most recent call last):
pypi-server   |   File "/usr/local/bin/pypi-server", line 8, in <module>
pypi-server   |     sys.exit(main())
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/pypiserver/__main__.py", line 203, in main
pypi-server   |     bottle.run(
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/pypiserver/bottle.py", line 3971, in run
pypi-server   |     server.run(app)
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/pypiserver/bottle.py", line 3804, in run
pypi-server   |     return sa(self.host, self.port, **self.options).run(handler)
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/pypiserver/bottle.py", line 3579, in run
pypi-server   |     serve(handler, host=self.host, port=self.port, _quiet=self.quiet, **self.options)
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/waitress/__init__.py", line 19, in serve
pypi-server   |     server.run()
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/waitress/server.py", line 322, in run
pypi-server   |     self.asyncore.loop(
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 245, in loop
pypi-server   |     poll_fun(timeout, map)
pypi-server   |   File "/usr/local/lib/python3.10/site-packages/waitress/wasyncore.py", line 172, in poll
pypi-server   |     r, w, e = select.select(r, w, e, timeout)
pypi-server   | ValueError: filedescriptor out of range in select()

**Comment by dee-me-tree-or-love** [comment]
Hey @Moggele, thank you very much for reporting this issue! 

Could you please give a few more details of your setup? 

1. What command did you use to start the `pypi-server` docker? 
2. Are you mounting any local volumes? 
3. What is your host (OS) system like?
