### ISSUE TITLE
missing distribution spec [pip 1.5.6, python 2.7]

### ISSUE THREAD

**Issue by kaos** [pypiserver/pypiserver#64]
Hi,

I run into this error when using a newer version of pip.

```
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

root@bc36f17fe2cc:/# pip install -r http://my-pypiserver/simple/ my-package
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1631, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '<html><head><title>Simple Index</title></head><body>')

```

When using pip 1.3.x (don't recall the exact version), it works just fine.

**Comment by ror6ax** [comment]
Hi Andreas,
`pip -r` is to be used with requirements file. If you need to install package via url you can simply do `pip install [url with full filename]`. Both work with current pypiserver and pip 6.0.3

**Comment by ror6ax** [comment]
ping @kaos

**Comment by ankostis** [comment]
@kaos is this issue invalid?

**Comment by kaos** [comment]
@ror6ax @ankostis Sorry, don't know how I've been able to miss the notifications for this issue..

No, I got the args mixed up with what I use with `setup.py sdist upload -r <repo>`.. My bad, sorry.

Thanks for pointing it out to me.
